### ISSUE TITLE
Ошибка AmoCRM.php

### ISSUE THREAD

**Issue by illusion-py** [drillcoder/AmoCRM_Wrap#12]
Добрый день!
При использовании вашей обёртки возникает след. ошибка:
Parse error: syntax error, unexpected '[' in AmoCRM_Wrap/src/AmoCRM.php on line 748

В зависимости от версии обёртки.
В 748 строке кода файла AmoCRM.php находится след. строка кода:
`$url = 'api/v2/' . (Config::$$attribute)['url'] . '?';`

Подскажите, как исправить или что я делаю не так?

Спасибо.

**Comment by drillcoder** [comment]
Возможно проблема была в версии php. Попробовал исправить это в версии v7.0.4

**Comment by illusion-py** [comment]
Спасибо! Проблема решена.
