### ISSUE TITLE
setCustomField Мультисписок не записывает значение

### ISSUE THREAD

**Issue by rizoen** [drillcoder/AmoCRM_Wrap#3]
`620191
Array
(
    [0] => DrillCoder\AmoCRM_Wrap\Helpers\Value Object
        (
            [value:DrillCoder\AmoCRM_Wrap\Helpers\Value:private] => Элита
            [enum:DrillCoder\AmoCRM_Wrap\Helpers\Value:private] => 0
            [subtype:DrillCoder\AmoCRM_Wrap\Helpers\Value:private] => 
        )

)

Сегмент`
Лог перед $customFieldObj = new CustomField($id, $valueObj, $name);
Похоже enum id не определяется.
И тут опечатка " В поле типа мультисписок значения вносятся с разделителем точка с запятоу (;)"

**Comment by rizoen** [comment]
foreach ($raw->custom_fields->leads as $field) {
            $this->idLeadCustomFields[$field->id] = $field->name;
            if ($field->field_type == 4) {
                $this->idLeadCustomFieldsEnums[$field->id] = json_decode(json_encode($field->enums), true);
            }
	        if ($field->field_type == 5) {
		        $this->idLeadCustomFieldsEnums[$field->id] = json_decode(json_encode($field->enums), true);
	        }
        }

**Comment by drillcoder** [comment]
Не совсем понял что именно не работает. 
Сейчас проверил 
`$contact->setCustomField(617095, '1;2');`
Сработало и поле заполнилось 2я значениями 1 и 2

**Comment by rizoen** [comment]
А в контакт и будет работать, в коде для контактов field_type == 5.
У меня пример для лида.
> 
Field Type
Parameter | Code | Description
-- | -- | --
4 | SELECT | A list type field with the ability to select one element
-- | -- | --
5 | MULTISELECT | A list type field with the ability to select multiple list items

**Comment by drillcoder** [comment]
Исправлено в версии 7
