### ISSUE TITLE
А для чего это сделано? Таким образом возвращаются не все контакты которые есть в CRM.

### ISSUE THREAD

**Issue by crazybee47** [drillcoder/AmoCRM_Wrap#4]
https://github.com/drillcoder/AmoCRM_Wrap/blob/aff95f11cf5f45d207810a32f256b6c447b86716/src/AmoCRM.php#L173

**Comment by drillcoder** [comment]
Таким образом происходит проверка что найден контакт именно с номером телефона т.к. если этот телефон или его часть будет записана в кастомном поле, допустим с кодом операции платежа (ну совпало так что там такие же цифры) что бы в выдачу не попал такой контакт.

**Comment by crazybee47** [comment]
Я столкнулся с такой ситуацией, когда контакт не возвращался вообще, хотя в црм было 2 Контакты с этим номером, убрал проверку и стало все хорошо

**Comment by drillcoder** [comment]
Исправлено в версии 7
