### ISSUE TITLE
Методы по работе с аккаунтом

### ISSUE THREAD

**Issue by bigperson** [drillcoder/AmoCRM_Wrap#6]
Не нашел метода по работе с данными аккаунта.
https://www.amocrm.ru/developers/content/api/account

**Comment by bigperson** [comment]
список пользователей, типов задач, кастомных полейк примеру

**Comment by drillcoder** [comment]
Добавил в документацию статичные методы у AmoCRM:: в которых можно получить информацию об аккаунте. Если требуется метод который вернёт всю информацию сразу, дайте знать)

**Comment by bigperson** [comment]
@drillcoder еще бы добавить метод, возвращающий запрошенную информацию по нескольким сущностям, а то лишние запросы к api. например сразу получить воронки пользователей и типы задач

**Comment by drillcoder** [comment]
Запросы к апи не делаются, вся информация достаётся при авторизации и храниться в объекте
